### ISSUE TITLE
Support Clang 12 on Linux

### ISSUE THREAD

**Issue by aminya** [atilaneves/libclang#23]
When I try to use this with Clang 12, I get such an error on Linux:

```
/home/runner/.dub/packages/dpp-0.4.4/dpp/bin/d++: error while loading shared libraries: libclang.so.10: cannot open shared object file: No such file or directory
Program exited with code 127
```

It seems it is still using `libclang.so.10`.

**Comment by atilaneves** [comment]
This project doesn't specify the version of clang at all. In all likelihood that `d++` binary was built with libclang 10.

**Comment by aminya** [comment]
This was actually related to the CI bug I fixed in 
https://github.com/atilaneves/dpp/commit/23490740129846b0d2daf40ea88ec1a7ccd0a471

We should improve the installation instructions in the documentation of dpp and libclang.
